### ISSUE TITLE
Multiple Files - FileList

### ISSUE THREAD

**Issue by mateusmx** [dropzone-ui/dropzone-ui-react#245]
Hi Guys, I'm working with the package for a while now, So far is working great with 1 file upload but for some reason I can't make it work with multiple files.

FIrst let me tell you my stack:
In the back I'm using as follows:
- Nodejs
- Express js
- Type-Graphql
- Typeorm

In the front:
- Nextjs
- MUI
- Apollo Client.

So this is what is happening:
- When I make a submit with 1 file, we have no issues, it gets upload, creates the url and everything works nice.
- The problem is when uploading multiple files. So far I've been trying to change everything in the back, and for some reason I'm unable to make it work.
- But when I try to make a simple <input type="file" multiple> it actually works the uploading.
- So what I was able to figure it out. Is that the component is giving me an array of files .... But for some reason the input is generating something called 'fileList' (unfortunately is read only so I can't create that object) so I tried to create an object from the array, but still I was unable to make it work (Adding some screenshots)

![Captura de Pantalla 2022-01-16 a la(s) 15 52 38](https://user-images.githubusercontent.com/14305038/149679817-50590ef9-f2fd-485e-b387-0ff161699579.png)

So my question is, is there any form we can make this 'fileList' as result when using multiple files instead of just making an array of files ? 

I'm happy to pair to figure out the issue/any solution, just send me an email (pablodiazmateus@gmail.com

Regards,

Pablo.

**Comment by JinSSJ3** [comment]
Hey Pablo,
We've just sent you a e-mail, please check your inbox.
Regards.
Jin
