### ISSUE TITLE
dropzone-ui.com is not working

### ISSUE THREAD

**Issue by etomarat** [dropzone-ui/dropzone-ui-react#343]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/710389/166198175-9a12994d-30bc-4e81-86f3-6f17e4c6aa8e.png">

**Comment by JinSSJ3** [comment]
Hey @etomarat , thanks for the alert.

There was a problem on the main server that is hosted on https://www.deelo.cloud
Please, if you need to acces to the webpage, you can use this link on heroku:

https://dropzone-ui.herokuapp.com/

regards

**Comment by etomarat** [comment]
> Hey @etomarat , thanks for the alert.
> 
> There was a problem on the main server that is hosted on https://www.deelo.cloud Please, if you need to acces to the webpage, you can use this link on heroku:
> 
> https://dropzone-ui.herokuapp.com/
> 
> regards

Thank you!

**Comment by corneliushka** [comment]
It will be great if the link is updated elsewhere, like on [npmjs](https://www.npmjs.com/package/@dropzone-ui/react) or even this GitHub repository.
People will think that it's not active anymore...

Good job with the package!

**Comment by JinSSJ3** [comment]
Thanks for your comments! Link is correctly updated.
