### ISSUE TITLE
is it't support show the latest selected file only if the maxFiles attribute is set to 1?

### ISSUE THREAD

**Issue by JoyCood** [dropzone-ui/dropzone-ui-react#407]
when i set the maxFiles={1}, the box aways show all the files i selected before, how to set the box only show the latest file i selected?

**Comment by JinSSJ3** [comment]
Hi @JoyCood !!!!
Could you please try adding "behaviour" prop to dropzone component?

```jsx
<Dropzone
  //other props 
  maxFiles={1}
  behaviour={"replace"}
>
</Dropzone>
```

**Comment by JoyCood** [comment]
> ```js
> behaviour={"replace"}
> ```

thank you very much, it is work!
