### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by alexbegt** [dropzone-ui/dropzone-ui-react#408]
Will there be an update to DropZone UI React to support React 18? Currently I am trying to upgrade my project to use 18 but I am unable to due to dropzone using react 17. I really like using DropZone UI and hope it will be upgraded soon.

**Comment by JinSSJ3** [comment]
Hey @alexbegt !!
Thanks for writting us!
We are currently working on a new version od Dropzone-ui that supports both React 17 and 18.
We'll notify you as soon we can deploy it!

**Comment by alexbegt** [comment]
> Hey @alexbegt !! Thanks for writting us! We are currently working on a new version od Dropzone-ui that supports both React 17 and 18. We'll notify you as soon we can deploy it!

Great thanks! Looking forward to this!

**Comment by JinSSJ3** [comment]
Hey there @alexbegt !

We've just deployed a new version of 🚀  [@dropzone-ui/react](https://www.npmjs.com/package/@dropzone-ui/react) (V.6.7.10) that supports react 18. Please give it a try and let us know if there is something missing.

Thanks in advance.

**Comment by alexbegt** [comment]
Hi @JinSSJ3 ,

I have given it a test, I noticed there's one thing that is now missing: I had set a custom Label text (Click here to upload your documents) but now the text is completely gone: 
![Uploading image.png…]()

**Comment by JinSSJ3** [comment]
Hi @alexbegt, this might happend due to a new update 🚀  in wich `children` has the highest priority.
You should add something like that:
```jsx
    <Dropzone
       label={"Click here to upload your documents"}
       {..otherProps}
      >
        {files.length > 0 &&    // 👀 add this statement 
          files.map((fileItemProps) => (
            <FileItem
              {...fileItemProps}
            />
          ))}
    </Dropzone>
```
or you can check this [samle](https://codesandbox.io/s/dropzone-ui-complete-946hz). 
Hope it works. If not, let us now 😄

**Comment by alexbegt** [comment]
Hi @JinSSJ3 That worked! Thank you so much for the fast reply.
