### ISSUE TITLE
Footer and Header className prop

### ISSUE THREAD

**Issue by davidbejarcaceres** [dropzone-ui/dropzone-ui-react#514]
**Is your feature request related to a problem? Please describe.**
We need a className prop for header/footer to be added to "dz-ui-header" "and dz-ui-footer".

**Describe the solution you'd like**
Add headerClassName footerClassName to specify custom className for header and footer like

```
<Dropzone
    headerClassName={"headerCustomClass"}
    footerClassName={"footerCustomClass"}
>
  ...
</Dropzone>
```

**Additional context**
I tried to specify more than 10 file types with "accept" prop, and the width of the footer is too long, we have a custom css class to wrap the words to prevent line goes offscreen, but there is no way to add our custom class to footer. You can see an example in the following image:
![image](https://user-images.githubusercontent.com/17320214/194504525-a75d7aaa-4800-483a-8ced-96c0072093cb.png)

**Comment by JinSSJ3** [comment]
Hey @davidbejarcaceres !!

Thanks for the feature request.
We added this feature in a new version 🚀 [V6.7.20](https://www.npmjs.com/package/@dropzone-ui/react). Also, you can check how it works in this [codesandbox](https://codesandbox.io/s/headerclassname-footerclassname-m6dudw) example.
Please, reinstall the package and 👀 try this new version out and let us know if this improvement solves your issue or if there is something else missing.

Thanks in advance.

**Comment by davidbejarcaceres** [comment]
This works perfectly.

Thanks!
