### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by kailinj** [dropzone-ui/dropzone-ui-react#555]
**Describe the bug**
Going to https://dropzone-ui.herokuapp.com/ renders a page with an Application Error from Heroku

**To Reproduce**
1. Go to https://dropzone-ui.herokuapp.com/
2. See error

**Expected behavior**
This URL would load the "Live demo and code generator", as indicated in the README

**Screenshots**
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/3209103/206792866-9d4de078-ff14-48e7-927a-cdac6d8fb00a.png">

**Desktop (please complete the following information):**
 - OS: OSX Ventura / 13.0.1 (22A400)
 - Browser: Chrome
 - Version: 108.0.5359.94 (Official Build) (arm64)

**Additional context**
N/A

**Comment by JinSSJ3** [comment]
Hi @kailinj !!! thanks for notifying this issue.

There was a problem in the server that host the webpage.
Please, visit the webpage in the new domain of [dropzone ui  webpage](https://dropzone-ui.vercel.app/)

Thanks in advance. Happy coding! 💻
