### ISSUE TITLE
Avoid calling githubusercontent to request image icon

### ISSUE THREAD

**Issue by khgar** [dropzone-ui/dropzone-ui-react#592]
Problem: 
You are actually calling url : https://user-images.githubusercontent.com/43678736/132086672-3a856fda-823d-4997-b802-c7c640e6ef44.png to download image icon inside the dropzone. I would like to avoid using external url. 

Idea:
It would be nice to set up image inside the repository or set up a param to request internal images.

**Comment by JinSSJ3** [comment]
Hi @khgar! ✋ 

Thanks for writting. In a nutshell, you want to use your own images or set up different URLs. It is not like this?

If so, let me tell you that we already considered how to allow the user to set custom image icons for a future release. And as soon as we have it done, we will let you know. ✉️ 

If not, could you please explain more about this behaviour? 👀

**Comment by JinSSJ3** [comment]
Hi @khgar , we've recently published 🚀  a new library [@files-ui/react](https://www.npmjs.com/package/@files-ui/react) in which we provide a way to avoid calling eternal urls by providing your own sources.

👀  Check it out in the new [webpage](https://www.files-ui.com/global-config);

**Comment by khgar** [comment]
Hi @JinSSJ3, thank you this is what I was looking for, I will take a look at the library quickly.
